spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://124.221.4.74:3306/user_center?useSSL=false'
    username: xiushi
    password: 2872573
  #session 失效时间
  session:
    timeout: 86400